OtoGaleri/OtoGaleri/Models/Car.cs
namespace OtoGaleri.Models;

public class Car
{
    public int CarID { get; set; }
    public string CarBrand { get; set; }
    public string CarModel { get; set; }
    public string CarDescription { get; set; }
    public string CarImage { get; set; }
    public int CarYear{ get; set; }
    public float CarKm { get; set; }
    public float CarPrice { get; set; }
}

OtoGaleri/OtoGaleri/Models/ErrorViewModel.cs
namespace OtoGaleri.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

OtoGaleri/OtoGaleri/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace OtoGaleri.Controllers;

public class AboutUsController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

OtoGaleri/OtoGaleri/Controllers/CarController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using OtoGaleri.Data;
using OtoGaleri.Models;

namespace OtoGaleri.Controllers;

public class CarController : Controller
{
    private readonly CarData _carData;

    [ActivatorUtilitiesConstructor]
    public CarController(CarData carData)
    {
        _carData = carData;
    }
    
    // GET
    public IActionResult Index(string id)
    {
        if (id != null)
        {
            var carList = _carData.carData.Where(x => x.CarBrand == id)
                .ToList();
            return View(carList);
        }
        else
        {
            return View(_carData.carData);
        }
    }
    
    [HttpGet]
    public IActionResult BuyCar(string id)
    {
        var findCar = _carData.carData.Where(x => x.CarID == int.Parse(id)).FirstOrDefault();
        _carData.carData.Remove(findCar);
        
        TempData["message"] = "Tebrikler aracımızı satın aldınız!";
        return RedirectToAction("Index");
    }

    
    [HttpGet]
    public IActionResult AddCar()
    {
        return View("AddCar");
    }

    [HttpPost]
    public async Task<IActionResult> AddCar(Car car, IFormFile uploadPhoto)
    {
        if (uploadPhoto != null)
        {
            string wwwRootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
            string fileName = Path.GetFileNameWithoutExtension(uploadPhoto.FileName);
            string extension = Path.GetExtension(uploadPhoto.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            car.CarImage = fileName;
            string path = Path.Combine(wwwRootPath + "/Assets/assets/carimg", fileName);
            using (var fileStream = new FileStream(path,FileMode.Create))
            {
                await uploadPhoto.CopyToAsync(fileStream);
            }
        }
        
        Random rnd = new Random();
        car.CarID = rnd.Next();;
        car.CarDescription = "test";
        
        _carData.carData.Add(car);
        TempData["message"] = "Araç başarıyla eklendi.";
        return RedirectToAction("Index");
    }
}

OtoGaleri/OtoGaleri/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using OtoGaleri.Data;
using OtoGaleri.Models;

namespace OtoGaleri.Controllers;

public class HomeController : Controller
{
    private readonly CarData _carData;

    public HomeController(CarData carData)
    {
        _carData = carData;
    }
    public IActionResult Index()
    {
        var carBrands = _carData.carData
            .Select(x => x.CarBrand)
            .Distinct();
        
        return View(carBrands);
    }
}

OtoGaleri/OtoGaleri/ViewComponents/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OtoGaleri.Data;

namespace OtoGaleri.ViewComponents;

public class BrandsViewComponent : ViewComponent
{
    
    private readonly CarData _carData;

    [ActivatorUtilitiesConstructor]
    public BrandsViewComponent(CarData carData)
    {
        _carData = carData;
    }
    
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var carBrands = _carData.carData
            .Select(x => x.CarBrand)
            .Distinct();
        
        RouteData.Values.Remove("id");
        return View("Index",carBrands);
    }
    
}

OtoGaleri/OtoGaleri/Views/AboutUs/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="bg bg-primary text-center fw-bold text-white"> Hakkımızda </h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias cumque dolor eveniet molestiae necessitatibus nemo numquam quidem quod, sed vel! Aliquid autem itaque minima necessitatibus pariatur praesentium quae quas quos! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus magni non omnis, possimus quas soluta ut. Commodi dolore esse facere, iste iure laborum magni, mollitia officia quaerat quas rem, tempora? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis commodi cumque dolore ex exercitationem incidunt libero molestiae necessitatibus placeat quo! Amet beatae corporis deleniti eius eum iste rem sed vel. </p>
</div>

OtoGaleri/OtoGaleri/Views/Car/AddCar.cshtml
@model Car

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="mb-3 bg bg-primary text-center fw-bold text-white"> Araba Ekle </h1>
    <form asp-controller="Car" asp-action="AddCar" enctype="multipart/form-data" method="POST" class="mt-2 mb-1" >
        <div class="form-group mt-2">
            <label for="CarBrand" class="text-dark">Marka</label>
            <input asp-for="CarBrand" required="required" required="required" type="text" placeholder="Marka girin" class="form-control" id="CarBrand" aria-describedby="nameHelp">
        </div>
        <div class="form-group mt-2">
            <label for="CarModel" class="text-dark">Model</label>
            <input asp-for="CarModel" required="required" type="text" placeholder="Model girin" class="form-control" id="CarModel" aria-describedby="nameHelp">
        </div>
       <div class="form-group mt-2">
           <label for="uploadPhoto">Araç Resmi</label>
           <div class="input-group">
               <div class="custom-file">
                   <input required="required" name="uploadPhoto" type="file" class="custom-file-input" id="uploadPhoto">
                   <label class="custom-file-label" for="uploadPhoto">Resim seçin</label>
               </div>
           </div>
           </div>
        <div class="form-group mt-2">
            <label for="CarYear" class="text-dark">Araç Yılı</label>
            <input asp-for="CarYear" required="required" placeholder="Araç yılı girin" class="form-control" id="CarYear" aria-describedby="nameHelp">
        </div>
        <div class="form-group mt-2">
            <label for="CarKm" class="text-dark">Araç Kilometre</label>
            <input asp-for="CarKm" required="required" placeholder="Araç kilometre girin" class="form-control" id="CarKm" aria-describedby="nameHelp">
        </div>
         <div class="form-group mt-2">
                    <label for="CarPrice" class="text-dark">Araç Fiyat</label>
                    <input asp-for="CarPrice" required="required" placeholder="Araç fiyat girin" class="form-control" id="CarPrice" aria-describedby="nameHelp">
                </div>
    <button class="btn btn-primary btn-lg btn-block mt-2">
       Oluştur
    </button>
    </form>

</div>

OtoGaleri/OtoGaleri/Views/Car/Index.cshtml
@model IEnumerable<Car>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["message"]
        </div>
    }
    
    @await Component.InvokeAsync("Brands")

    <h1 class="mb-3 bg bg-primary text-center fw-bold text-white"> Arabalarımız </h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Resim</th>
            <th scope="col">Marka</th>
            <th scope="col">Model</th>
            <th scope="col">Yıl</th>
            <th scope="col">Km</th>
            <th scope="col">Fiyat</th>
            <th scope="col">Satın Al</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <th><img width="100" height="100" class="" src="~/Assets/assets/carimg/@(car.CarImage)" alt=""></th>
                <td>@car.CarBrand</td>
                <td>@car.CarModel</td>
                <td>@car.CarYear</td>
                <td>@car.CarKm KM</td>
                <td>@car.CarPrice ₺</td>
                <td> <a class="btn btn-success" data-bs-id="@car.CarID" data-bs-toggle="modal" data-bs-target="#basicModal-@car.CarID">Satın Al</a></td>
            </tr>
        }
        </tbody>
    </table>
</div>

@foreach (var car in Model)
{
    <!-- basic modal -->
    <div id="basicModal-@car.CarID" class="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Satış</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Aracı satın almak istiyor musunuz?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Vazgeç</button>
                    <a asp-route-id="@car.CarID" asp-controller="Car" asp-action="BuyCar"><button  type="button" class="btn btn-primary">Satın Al</button></a>
                </div>
            </div>
        </div>
    </div>
}

OtoGaleri/OtoGaleri/Views/Home/Index.cshtml
@model IEnumerable<string>

@{
    ViewData["Title"] = "Home Page";
}

<h1 class="bg bg-primary text-center fw-bold text-white"> Markalarımız </h1>
<div class="mt-3 row">
    @foreach (var car in Model)
        {
            <div class="text-center mt-2 col-md-3">
                <a asp-route-id = "@car"  asp-controller="Car" asp-action="Index">
                    <div class="card border border-primary" style="width: 18rem;">
                        <img class="rounded img-thumbnail card-img-top" width="2048" height="2048" src="~/Assets/assets/img/@(car).png" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@car</h5>
                        </div>
                    </div>
                </a>
            </div>
        }
    
</div>

OtoGaleri/OtoGaleri/Views/Shared/Components/Brands/Index.cshtml
@model System.Collections.Generic.IEnumerable<string>

<div class="mt-4">
    <h1 class="mb-3 bg bg-primary text-center fw-bold text-white"> Markalarımız </h1>
    <div class="row">
        @foreach (var carModel in Model)
        {
            <div class="mb-3 ml-1 mr-3 border border-primary px-1 py-3 col-md-3">
               <span><img width="25" height="25" src="~/Assets/assets/img/@(carModel).png" alt=""></span> <a asp-route-id="@carModel" asp-controller="Car" asp-action="Index">
                    @carModel
                </a>
            </div>
        }
    </div>
</div>

OtoGaleri/OtoGaleri/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Oto Galeri</title>
        <link rel="icon" type="image/x-icon" href="~/Assets/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="~/Assets/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar bg bg-primary navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Oto Galeri</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Car" asp-action="Index">Arabalarımız</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Car" asp-action="AddCar">Araba Ekle</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="AboutUs" asp-action="Index">Hakkımızda</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('Assets/assets/img/banner04.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Oto Galeri</h1>
                            <span class="subheading">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum enim in incidunt magni voluptas? Assumenda blanditiis consequatur dolores doloribus earum, illum labore magni nihil odit, quae, quaerat quidem tempora vel.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            @RenderBody()
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Oto Galeri 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="~/Assets/js/scripts.js"></script>
    </body>
</html>